ARG TERRAFORM_VERSION=v1.9
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v2.1.0-fedora

ARG TARGETPLATFORM

USER root

## AWS cli
RUN dnf install -y \
        awscli && \
    dnf clean all && \
    aws --version

USER devops
