ARG TERRAFORM_VERSION=v1.9
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v2.1.0-alpine

ARG TARGETPLATFORM

USER root

## AWS cli
RUN apk add --no-cache --force-broken-world \
        aws-cli && \
    rm -rf /var/cache/apk/* && \
    aws --version

USER devops
