ARG TERRAFORM_VERSION=v1.2
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v1.4.20-fedora

ARG TARGETPLATFORM

## AWS cli
RUN sudo dnf install -y \
        python3 \
        python3-pip \
    && sudo pip3 install --upgrade pip \
    && sudo pip3 install awscli \
    && sudo dnf clean all \
    && aws --version
