ARG TERRAFORM_VERSION=v1.2
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v1.0.2-alpine

ARG TARGETPLATFORM

## AWS cli
RUN sudo apk add --no-cache \
        python3 \
        py3-pip \
    && sudo pip3 install --upgrade pip \
    && sudo pip3 install awscli \
    && sudo rm -rf /var/cache/apk/* \
    && aws --version
